### ISSUE TITLE
Build Basic English Auction Contract

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/DES484-NFT-Auction#1]
# Background
We have the template code from pic's vending machine. I feel obliged to continue by working on the final english auction contract.

# To Do
- My own branch `grapes/english-auc` from `pic/try-NFT-auction`
- I'd write into the folders pic created. Once done, we can PR into her branch.
- Logic
  - [x] Assume owner `msg.sender` is the host of the contract. Needs `nft_tok_id` and `end_time` as parameters
  - [x] Any bidders can bid. Once bid, the contract locks the money away
  - [x] Track the current highest bidder, and bid value
  - [x] If next bidder is higher, update the current highest, locks money, and return the previous money back
  - [x] After set time, transfer money to owner `msg.sender`
  - [x] If nobody bids, returns the NFT to seller

### Things To Test
- Might need to mint some NFTs to test this.
- [x] The bidding process works. 
  - [x] Bidder gets their money locked into the contract. (Might need to have a contract balance check function).
  - [x] Bidder gets their money automatically returned upon higher bidder. The new bidder will get their money locked instead
- [x] The rewarding process works
  - [x] Bidder gets NFT
  - [x] Seller gets money

**Comment by NanoniPck** [comment]
Note: the template only includes vendingmachine and the folders inside this folder. Other folders outside of vendingmachine are just for my own testing. Not sure if it's gonna work.

**Comment by GrapesGoober** [comment]
# How Can I Test?
- I need multiple accounts. The `test_auction.js` gave one variable: `accounts` array. I don't know whether this has more than 1 accounts to test.
- Need to mint NFTs. Just this token ID for the constructor
- Need to test auction expired revert logic. In testing, I set the expire to 1 minute. Might need to redefine a new testing auction that lasts for 5 seconds, or something
- Need to test that various accounts gets refunded and rewarded with the correct NFT. Might need to try multiple NFTs.

**Comment by GrapesGoober** [comment]
# Done, Whoohooo
- PR in #2
